### ISSUE TITLE
XmlError : For security reasons DTD is prohibited in this XML document

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/odata-routing-policy#7]
Error parsing OData V2 service description. 

We are getting the following error when trying to parse:
```
Unhandled Exception: Microsoft.Data.Edm.Csdl.EdmParseException: Encountered the following errors when parsing the EDMX document:
XmlError : For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method. : (0, 0)
   at Microsoft.Data.Edm.Csdl.EdmxReader.Parse(XmlReader reader)
   at OdataSwaggerConverter.Program.Main(String[] args)
```

Can you @rathnapandi  please check, if this can be fixed/enhanced? Unfortunately, we cannot share the Meta-Data file.

Thanks!
Chris

**Comment by rathnapandi** [comment]
Not a defect. could not reproduce the issue.
